[opcache]
; 0 means it will check on every request
; 0 is irrelevant if opcache.validate_timestamps=0 which is desirable in production
opcache.enable=1
opcache.enable_cli=1
opcache.revalidate_freq=0 ; development
;opcache.revalidate_freq=60 ; production
opcache.validate_timestamps=1
opcache.max_accelerated_files=10000
;opcache.memory_consumption=192
opcache.memory_consumption=1024
opcache.max_wasted_percentage=10
;opcache.interned_strings_buffer=16
opcache.interned_strings_buffer=32
opcache.fast_shutdown=1
; opcache.preferred_memory_model=mmap
opcache.log_verbosity_level=1
opcache.error_log=/var/logs/opcache.log
