[xdebug]
#xdebug.mode = debug,profile,trace
xdebug.mode = debug
#xdebug.start_with_request = yes
xdebug.start_with_request = trigger
#xdebug.discover_client_host = 0
xdebug.discover_client_host = 1
xdebug.client_port = 9203
xdebug.client_host=host.docker.internal
xdebug.idkey=docker-cli
xdebug.use_compression = true